### ISSUE TITLE
Member Manage list does not work

### ISSUE THREAD

**Issue by SRNovels** [kanadaj/RoyalRoadLegends#100]
I was going to add a new member to are group Scribble but when I went to do so the link I use to get there does not work -link=http://royalroadl.com/forum/managegroup.php?gid=20. There isn't any other link you can use to get there, so for right now there is a 0 possibility to add new members that you can eat to.

**Comment by SRNovels** [comment]
Get*

**Comment by kanadaj** [comment]
http://forum.royalroadl.com/managegroup.php?gid=20
