### ISSUE TITLE
Latest Updates page doesn't show fiction ratings

### ISSUE THREAD

**Issue by Ultrabenosaurus** [kanadaj/RoyalRoadLegends#101]
From a user's perspective, showing the ratings in search results helps us to not waste our time and enthusiasm by opening ToC pages for fictions with very low ratings - which usually means they're not worth reading, and have probably been dropped by the author as well. Honestly, title, tags, and rating are the 3 most important things for an RRL fic. I can't even remember how many fics I have enjoyed that had terrible summaries, but had all the tags I like and a 4+ star rating!

From RRL's perspective, showing the ratings means people can tell at a glance if a fic is worth paying attention to before opening the ToC page - this leads to fewer connections to the web server (when reloading my reading list I'm seeing only 7 of 61 requests being served by my browser's cache) and thus you use less bandwidth and the server only has to exert a fraction of the effort to add ratings into search results compared to loading a whole new page. Would this not help with running costs on top of improving load times and increasing the maximum concurrent users that can be served?

**Comment by curvinho** [comment]
Those points would be valid if the objective of latest updates was for people to find popular stories to read. The ratings were removed from sight so people would stop using them as main factor when deciding what to read and give a chance to new and not yet popular stories. If you wish to find something based on ratings alone, use the search.
