### ISSUE TITLE
Time-Format Setting does not carry over to Quotes

### ISSUE THREAD

**Issue by mjkj** [kanadaj/RoyalRoadLegends#103]
The time format setting works well on the times shown on the comments themselves (I have set it to 24:00 hrs without the (IMO annoying) am/pm display) - but for the time stamp of the quotes it does not show the selected format but always shows the time with AM/PM (and in all capital letters at that!). (Examples see here: [http://royalroadl.com/fiction/chapter/97145](url))

Could you please change that? Thank you :smiley: 

This might go together with #102 

Label: Enhancement? Bug?

**Comment by kanadaj** [comment]
Those quotes have plain text dates, can't be converted.
