### ISSUE TITLE
Fics with too many chapters updates can break layout (homepage)

### ISSUE THREAD

**Issue by Edward-Castle** [kanadaj/RoyalRoadLegends#11]
![image](https://cloud.githubusercontent.com/assets/899509/19138638/5f372946-8b54-11e6-9c7c-ed90ef8f90e8.png)

**Comment by kanadaj** [comment]
This one is known, but what the hell can we even do about it? :/

**Comment by progandy** [comment]
You could run a javascript that synchronizes the height
Or show only a few updates and display the rest on hover/focus.

**Comment by Edward-Castle** [comment]
@kanadaj I like @progandy idea of showing a couple chapters for each updated fic and a hover-thing to show more.

Maybe something like:

Chapter 2: Some title of mine
[(...)](#)
Chapter 34: More stuff
