### ISSUE TITLE
Reviews appearing blank (mobile)

### ISSUE THREAD

**Issue by DocteurNS** [kanadaj/RoyalRoadLegends#112]
On mobile, some reviews show no text, be it in [show less], [show more], in dark or light theme.

![](http://i.imgur.com/Kuofl3F.jpg)

**Comment by kanadaj** [comment]
Can you link an example page?

**Comment by DocteurNS** [comment]
Well, it's a bit everywhere, but for example:
Here: http://royalroadl.com/fiction/7599, the review "Glorious Chaos" appears blank. Also "Too crazy?" and both reviews on page two.
Here: http://royalroadl.com/fiction/7183, it's the same for "I like this" and "when sci-fi meets fantasy".

**Comment by kanadaj** [comment]
Hmm I think this is an issue of text overflow. Not sure yet how to fix, it's due to an extremely tiny screen resolution.

**Comment by kanadaj** [comment]
Yep, removing the portlet's padding under 260px width seems to fix the issue. Fix goes up with next update.
