### ISSUE TITLE
Being logged out, trying to rate a novel and then loggin in after being prompted to, will lead you to wrong page.

### ISSUE THREAD

**Issue by QuDubz** [kanadaj/RoyalRoadLegends#116]
If you are logged out and try to rate one of the novels, you will be prompted to log in, in order to rate the novel.

After loggin in, the site will transfer you to the following page:

http://royalroadl.com/fictions/rate/4293
http://i.imgur.com/MZ7Y33S.png

Which does not work.

**Comment by kanadaj** [comment]
Fixed with next patch
