### ISSUE TITLE
white space on mobile phone because of nested quotes

### ISSUE THREAD

**Issue by mjkj** [kanadaj/RoyalRoadLegends#119]
I again have experienced a white space on my mobile phone while reading a story on RRL. I believe that it is because of nested quotes that push the action button to the right over the edge of the page, therefore creating said white space. I experienced this on page [http://royalroadl.com/fiction/chapter/99047](http://royalroadl.com/fiction/chapter/99047) (see screenshot below).

I think that connects with #30 and #84 and #118

![screenshot_20161022-081057](https://cloud.githubusercontent.com/assets/22667034/19617441/974dc55e-9830-11e6-813a-12f13eb11661.png)

**Comment by mjkj** [comment]
...and again I experienced a table breaking the page: [http://royalroadl.com/fiction/chapter/99077](url) (see screenshot)

**Comment by kanadaj** [comment]
Ugh... now how do I fix this one...

**Comment by mjkj** [comment]
Sorry, I do not know - I hope you will find a solution...

**Comment by n0tj0nn0** [comment]
Huh, and here I thought that was to differentiate the quote contents from the post contents. Tee-hee.

**Comment by Ultrabenosaurus** [comment]
I've not looked at the HTML to see if it's immediately possible, but you could try fiddling with the CSS overflow properties of the containing elements. It'd mean that instead of the whole page having horizontal scroll only the table/comment that needs it would.

**Comment by kanadaj** [comment]
Tables have been modified to have a container already, not sure what to do about the comments yet, might just make the comment itself hide overflow and scroll.
