### ISSUE TITLE
Quote option in comments

### ISSUE THREAD

**Issue by mjkj** [kanadaj/RoyalRoadLegends#121]
Could you please add a "insert quote" option to the comment editor - thank you.
(I would suggest one entry under the "insert" section ("insert quote") and one under the "edit" section ("paste as quote") if possible)

It is really hard to get all the connected html/css code right for the quote to actually look like a quote.

Some days ago it still worked if I put the bbcode [quote] in and I got a (somewhat passable) quote back - that did not work today though (maybe because I used several of them in a row?)...

Label: enhancement

**Comment by progandy** [comment]
The editor is also missing some css. At least ```bootstrap.min.css``` should be included to get the white line one the left of a quote in the editor.

If you wish to create a quote manually, use
```
<blockquote><cite>{DATE, AUTHOR}</cite>
<p>{QUOTE HERE}</p>
<p>{OPTIONAL MORE PARAGRAPHS}</p>
</blockquote>
```
