### ISSUE TITLE
Can't exclude Female Lead tag without Male Lead tag being automaticaly excluded as well.

### ISSUE THREAD

**Issue by tonythereader** [kanadaj/RoyalRoadLegends#123]
It's basically what I said in the subject, I can't seem to exclude the Female Lead tag without it automatically excluding the Male Led tag as well. I can add a Male Lead tag and exclude the Female Lead but then the stories Have to have the Male Lead tag in them. It's not a big problem but if you could look at it I would really appreciate it. Thanks.

**Comment by kanadaj** [comment]
Fixed

**Comment by tonythereader** [comment]
Thank You.

**Comment by tonythereader** [comment]
Thank you very much. 😁
