### ISSUE TITLE
deleting pm results in page not found

### ISSUE THREAD

**Issue by mjkj** [kanadaj/RoyalRoadLegends#132]
When deleting a pm - be it from the inbox or from the trash can - the page loading results in a page not found error because the url is not constructed correct: //forum.royalroadl.com appears doublicated in it [http://forum.royalroadl.com//forum.royalroadl.com/private.php](url)

Might be related to #128 

Lable: Bug

**Comment by mjkj** [comment]
Same applies to moving items

(the moving and deleting still gets done.)

**Comment by Ultrabenosaurus** [comment]
I've deleted a few PMs recently, the day before you posted this and yesterday, but never had this issue.

**Comment by mjkj** [comment]
Well, it is still the case here (just tried again)

Maybe it is because of the browser? I use FF on windows and android (and yes, it happens not only on one device)

**Comment by kanadaj** [comment]
This seems like a browser issue, // nomally means "same protocol URL" (i.e. HTTP or HTTPS) but it might be causing trouble on Firefox. I'll check.

**Comment by kanadaj** [comment]
Can't reproduce.
