### ISSUE TITLE
Unpublished chapters change bookmark order and show in RSS

### ISSUE THREAD

**Issue by progandy** [kanadaj/RoyalRoadLegends#133]
In grouping mode the bookmarks show fictions with unpublished chapters in the wrong position, e.g.
```
# Fiction 1
Chapter X - 2 hours ago
# Fiction 2 <- has unpublished chapter
Chapter Y - 5 days ago
# Fiction 3
Chapter Z - 6 hours ago
```
Additionally, unpublished chapters are visible in the RSS feed. If I try to open the link from there I get
```
You do not have permission to view this directory or page.
```

**Comment by kanadaj** [comment]
Fixed with the next patch.
