### ISSUE TITLE
Advanced Search page "Fiction Details" section lacking relevant information

### ISSUE THREAD

**Issue by Edward-Castle** [kanadaj/RoyalRoadLegends#16]
http://royalroadl.com/fictions/search

It doesn't show what I expected (ratings, stuff); instead, it shows the first few paragraphs of fic's first chapter.

Personally, I like the idea, but maybe you could also add other relevant information?

It might be just me, though. If so, I'm sorry.

**Comment by curvinho** [comment]
No
