### ISSUE TITLE
Favorite and Read Later bookshelves swapped (reader bookshelf)

### ISSUE THREAD

**Issue by Edward-Castle** [kanadaj/RoyalRoadLegends#24]
I have one fic in in Bookmarks shelf, one in the Favorites shelf, and none at Read Later.

When I access my bookshelves ( http://royalroadl.com/my/bookshelf ) I see Favorite fic in place of Read Later.

When I click on any of the options, though, I view the right fics in the right shelves.

**Comment by starwarscards** [comment]
have the same thing happening to me just the wrong picture in the wrong spot.
![bookshelf](https://cloud.githubusercontent.com/assets/22653031/19141764/30563380-8b66-11e6-8271-2f152e1decfa.png)

**Comment by curvinho** [comment]
Fixed
