### ISSUE TITLE
No newest fiction list 

### ISSUE THREAD

**Issue by Rewritebywhocares** [kanadaj/RoyalRoadLegends#25]
The newest fiction list was a great way to give new authors the initial hits they needed to start rising up the other lists. Without it, it may become harder for new works to become popular (leading to stagnation) The trending list helps a little but it still requires an initial boost, which will be harder to get now.

**Comment by MariaWing** [comment]
You can still see the newest fiction list, it is simply not on the front page anymore. 
http://royalroadl.com/fictions/new-releases
