### ISSUE TITLE
White space right of chapter(maybe other pages as wel) on mobile

### ISSUE THREAD

**Issue by defnoob** [kanadaj/RoyalRoadLegends#30]
I noticed that when loading a chapter you will get white space to the right which goes away after the page has been fully loaded. There is an [exception](http://royalroadl.com/fiction/chapter/96366) to this however.

On my phone, the line of #'s at the end of his note prevents the white space from being removed. I'm assuming that it doesn't properly overflow to the next line because it's a special char? Idk.

**Comment by mjkj** [comment]
I had the same occurrence - only it was a table that got too wide (sorry I do not remember which site it was).

...could you maybe switch the color of that space to black for the dark theme?

**Comment by defnoob** [comment]
It was already set on the dark theme.

**Comment by mjkj** [comment]
@defnoob: that was not in question - I had mine set also to the dark theme when it occurred - that was meant as a suggestion for the devs to blacken the white space... :)

**Comment by kanadaj** [comment]
Fixed a while ago. It was present for chapters that had words too long for the page.

**Comment by mjkj** [comment]
I just got this problem with the white space just now at [http://royalroadl.com/fiction/chapter/96932](url)

**Comment by kanadaj** [comment]
Fixed

**Comment by mjkj** [comment]
Thank you :)
