### ISSUE TITLE
Page count not accurate

### ISSUE THREAD

**Issue by pietje1324** [kanadaj/RoyalRoadLegends#31]
Search result showed a page count of 187 while the table of contents showed only one announcement page.

Fiction where I encountered this:
http://royalroadl.com/fiction/3814

**Comment by kanadaj** [comment]
Fiction word counter doesn't respect chapter visibility

**Comment by kanadaj** [comment]
Chapters not visible to non-admins

**Comment by kanadaj** [comment]
Chapters are deleted; fiction length should be recalculated.

**Comment by mjkj** [comment]
It seems to me, that the page count maybe shows the combined count of fiction pages plus the comment pages or something like that...
...[http://royalroadl.com/fiction/8100](url) for example had 1000 pages yesterday, after today's update it shows 1014 pages (page count according to the bookmark site) - actual page count is 132 (according to fiction landing page where the chapter links are shown)

**Comment by kanadaj** [comment]
> page
> noun
> one of the leaves of a publication or manuscript; also :  a single side of one of these leaves.

A page usually contains between 250 and 275 words.
