### ISSUE TITLE
Polls not showing and can't edit my comments

### ISSUE THREAD

**Issue by Str1keFreedom00** [kanadaj/RoyalRoadLegends#33]
Hello with the new website or layout the polls arn't showing when i try and make one and i cant edit a comment that i made it goes to page can't be found...

**Comment by erowarrior** [comment]
Also when you want to create the poll, if you click on add option a white box will show that the writing color in it is white and you cant see what you write.

p.s: i use the dark theme

**Comment by unice5656** [comment]
Comments can't be deleted, either

**Comment by unice5656** [comment]
Old polls from before the update are not present

**Comment by kanadaj** [comment]
Old polls have been fixed, but comment editing might be buggy, gotta check
