### ISSUE TITLE
RSS doesn't work

### ISSUE THREAD

**Issue by EvilGremlin** [kanadaj/RoyalRoadLegends#35]
And please, return RSS button to fiction page.

**Comment by schannall** [comment]
Yes please!

**Comment by kanadaj** [comment]
There is an RSS feed under http://royalroadl.com/syndication/403,123?count=50
The above link is an RSS feed for fictions under ID 403 and 123 with up to 50 entries. I'll add an RSS button when things are stable.

**Comment by schannall** [comment]
@kanadaj : perfect, thank you!

sC

**Comment by QuDubz** [comment]
Is it possible for you guys to add the book name in RSS feeds?

When using an RSS feed with multiple novels, most of the novels will just be called "Chapter XX", making it almost impossible to know what novel it is, without manually checking all the feeds.

For example, this feed (Not the best example):

http://royalroadl.com/syndication/7707,6722,8312,4293,5701,7209,3442?count=15

Looks like this: 

![image](https://cloud.githubusercontent.com/assets/22663971/19159998/9a9f0842-8bee-11e6-8360-f4d28843892a.png)
