### ISSUE TITLE
Ctrl+click on fiction page opens chapter in the same tab

### ISSUE THREAD

**Issue by EvilGremlin** [kanadaj/RoyalRoadLegends#36]
Firefox 49.0

**Comment by Edward-Castle** [comment]
+1 for Google Chrome 53.0.2785.116 (64-bit)

**Comment by DocteurNS** [comment]
Same for me. Using CTRL+click to open a chapter when **on the fiction page** doesn't open said chapter in a new tab but just opens it normally. I haven't noticed the same problem anywhere else. It's not exactly a critical issue, but I still find it midly annoying.

And I use Chrome btw. If that matters.
