### ISSUE TITLE
No "Preview" Button For Chapters

### ISSUE THREAD

**Issue by DarkClaymore** [kanadaj/RoyalRoadLegends#41]
There's no "Preview" option for submitting/editing chapters.

**Comment by Lellith** [comment]
Yes, Im finding this a bit of a problem aswell, as I write in Google Docs, the text sometimes look 'funny' when placed over in RR. 
I hope we get a new preview thing soon :) that would be a great help.

Thanks for your hard work on RR

**Comment by kanadaj** [comment]
Do you mean chapters?

**Comment by DarkClaymore** [comment]
Yeah, chapter submissions.
Wrote this before realizing that the forum's layout didn't change. Sorry.

**Comment by progandy** [comment]
I think the chapter editor should use the same css styles as the chapter page, that should help.

**Comment by kanadaj** [comment]
I’m fairly sure it has the styles, doesn’t it?

**Comment by progandy** [comment]
It doesn't use all of them. At minimum, tinymce should be initiated with ```body_class: 'chapter-inner chapter-content'```, so that e.g. tables are blue. I think it would also be a good idea to add the bootstrap.min.css so that the fonts use the same default (sans serif) as in the published chapter.

By the way, here is some dirty code I threw together for a preview.
```
  // preview for chapter editor
  var textareas = document.getElementsByTagName("textarea");
  if (textareas) {
    $("body").append('<div class="modal fade" id="chapterPreview" tabindex="-1" role="dialog" aria-labelledby="chapterPreviewLabel" aria-hidden="true"> \
    <div class="modal-dialog" role="document"> \
      <div class="modal-content"> \
        <div class="modal-header"> \
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"> \
            <span aria-hidden="true">&times;</span> \
          </button> \
          <h4 class="modal-title" id="chapterPreviewLabel">Chapter Preview</h4> \
        </div> \
        <div class="portlet light chapter modal-body"> \
          <div id="previewContent" class="chapter-inner chapter-content"> \
          </div> \
        </div> \
      </div> \
    </div> \
  </div>');
    $('#chapterPreview').on('show.bs.modal', function (event) {
      var button = $(event.relatedTarget);
      var id = button.data('chapter');
      $(this).find('#previewContent').html(window.tinymce.get(id).getContent());
});
    for (var i = 0; i < textareas.length; ++i) {
      $(textareas[i].parentNode).append('<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#chapterPreview" data-chapter="'+textareas[i].id+'">Chapter Preview</button>');
    }
  }
```
