### ISSUE TITLE
Search-Function in Forum not working fine

### ISSUE THREAD

**Issue by iorgreths** [kanadaj/RoyalRoadLegends#43]
Everytime I am trying to use the search-function (-> button in the top-right beneath the user-profile)
![search_button](https://cloud.githubusercontent.com/assets/1315814/19156470/46645e28-8be2-11e6-82c6-dbf7930ee412.PNG)
![search_text](https://cloud.githubusercontent.com/assets/1315814/19156481/4c27ae28-8be2-11e6-99b8-dc55dad8e61a.PNG)

I get the following error-message instead of a reply:

> Fatal error: Call to undefined method dbpdoEngine::supports_fulltext_boolean() in D:\home\site\wwwroot\search.php on line 1487

This happens only if the URL starts with "forum.royalroadl.com"
![image](https://cloud.githubusercontent.com/assets/1315814/19156500/5f509b0e-8be2-11e6-87cf-6e35480b9889.png)

**Comment by kanadaj** [comment]
Fixed
