### ISSUE TITLE
Page 2 of latest update

### ISSUE THREAD

**Issue by Sil0ver** [kanadaj/RoyalRoadLegends#49]
I get '' the page you are lookinh for cannot be found'' trying to load the page

**Comment by wsensor** [comment]
Is that the link from the main page?
It links to http://royalroadl.com/fictions/lastest-updates
There is an s before the r in latest update.

**Comment by wsensor** [comment]
I meant an extra s before the t in latest

**Comment by Sil0ver** [comment]
http://royalroadl.com/fictions/latest-updates/2/#results 
Its this page that doesnt laod for me
