### ISSUE TITLE
Pagination is inconsistent between desktop and mobile

### ISSUE THREAD

**Issue by Ultrabenosaurus** [kanadaj/RoyalRoadLegends#55]
I use the latest stable Chrome, on Windows 10 Pro for desktop and Android 7.0 for mobile.

Using [Forgotten Conqueror](http://royalroadl.com/fiction/1439) as an example, when on desktop page 4 of the chapters list shows records 61 to 80 (B2C11 to B2C30) but on mobile page 4 shows records 31 to 40 (B1C29 to B1C38).

While reducing content on mobile layouts often makes sense, something like pagination of a results list would, ideally, be consistent. It makes switching from desktop to mobile quite confusing, as chapters are not where you expect them and you have to go page-by-page again to find the one you want. A list of chapters with the dates they were posted is a very small amount of content, cutting it from 20 to 10 rows saves very little data/bandwidth and doesn't improve user experience so it's a pointless design choice, really.

**Comment by kanadaj** [comment]
The problem is that 20 rows on mobile requires a lot of scrolling up and down
