### ISSUE TITLE
No Saved Drafts

### ISSUE THREAD

**Issue by NothingToSeeHereMoveAlong** [kanadaj/RoyalRoadLegends#56]
Like the title says, I for one cannot access my saved drafts. Or, more accurately, it's like they don't exist. I have not deleted them, i'm sure, but whenever I go to Saved Drafts... Well, they aren't there. It's been quite some time since i have noticed this. Ever since the new update, my saved drafts are simlpy gone. I don't know if others have been having this problem but at least i'm sure I do. Is this something that is fixable or am I going to have to start from scratch? I had two chapters almost ready and they were pretty long, so I really hope this problem can be resolved soon.

**Comment by kanadaj** [comment]
We'll look into making a new draft system and copying older drafts over. They are definitely there but there has been a bug with the indices that causes this behaviour. Sadly this is an under-the-hood issue and we have very little that can directly fix it.
