### ISSUE TITLE
weekly popular page

### ISSUE THREAD

**Issue by mataneloro** [kanadaj/RoyalRoadLegends#58]
so i want to check weekly popular page because thats where my usual go to page

and i scrolled down and then next page

then i notice there are many old fic in the list i.e http://royalroadl.com/fiction/58

so i open it

voila i redirected to error 500 page

is this bug or there are many old fic become popular again this week?

**Comment by curvinho** [comment]
Is it still not working?
Can you provide a screenshot of the issue?

**Comment by Noppes** [comment]
Im not getting error 500 pages, but it is clearly not working

Number 1 and 2 are on hiatus
And number 3 and 4 have both deleted all their chapters months ago. I highly doubt these are the most popular this week.

**Comment by Noppes** [comment]
![0cc8c0eb609136a8e74be3ffd2d46ae7](https://cloud.githubusercontent.com/assets/1127987/19279374/6e833b42-8fe1-11e6-893b-edb917a9e47e.png)

**Comment by Noppes** [comment]
Seems to work now
