### ISSUE TITLE
Latest Update Page 2 Leads to 404 Error

### ISSUE THREAD

**Issue by Greenfish106** [kanadaj/RoyalRoadLegends#68]
This was already listed, but that issue was closed while the problem is still existent and highly relevant.

Attempting to access page 2 of the latest updates results in being directed to http://royalroadl.com/fictions/latest-updates/2/#results

It is impossible to access page 2 of the latest updates currently due to this issue.

**Comment by curvinho** [comment]
That's the wrong url.
Use the navigation bar at the end of the list to navigate.
