### ISSUE TITLE
RSS updates display dates incorrectly.

### ISSUE THREAD

**Issue by TUSF** [kanadaj/RoyalRoadLegends#73]
When I look at any RSS feed, either with multiple or single entries, the dates give the impression that I traveled back in time.

    <pubDate>Sat, 17 Jan 1970 23:08:42 Z</pubDate>
    <a10:updated>1970-01-17T23:08:48Z</a10:updated>

I'm not really sure what the cause of this behavior is, but I'm guessing it may be due to using the wrong variable as a timestamp?

**Comment by EvilGremlin** [comment]
Yeah, that slightly above zero timestamp looks like input data format is wrong.

**Comment by TUSF** [comment]
Looks like the dates on the RSS are fixed. So I'll just close this.
