### ISSUE TITLE
Pagination only has start/end

### ISSUE THREAD

**Issue by kispin** [kanadaj/RoyalRoadLegends#74]
The Search pages (and forums) only have First 1..2..3 Last with no Next/Prev, this makes it annoying to try to go to the next page in a search that has more than 3 or 4 pages of results.

This is not a bug but a usability issue.

Note: It is more obvious because the Fictions pages DO have Next/Prev Buttons
Kispin

**Comment by progandy** [comment]
I prefer to have Prev/Next, too. 
Currently I am running my own userscript to add what I feel is missing, including prev/next.
https://git.io/vP029

**Comment by curvinho** [comment]
Fixed
