### ISSUE TITLE
Search function gives additional unrelated results

### ISSUE THREAD

**Issue by pietje1324** [kanadaj/RoyalRoadLegends#76]
When I searched for titles with the word "Vina", I also got "Smiling monk of death" as a result.

link: http://royalroadl.com/fictions/search?keyword=vina&name=&author=&minPages=0&maxPages=10000&status=ALL&orderBy=popularity&dir=desc

schreenshot: 
![screenshot](https://cloud.githubusercontent.com/assets/5565575/19212900/2e3c022a-8d5d-11e6-8557-5f866a5a9c51.png)

I hope this helps.

**Comment by kanadaj** [comment]
You've used keyword search, not title search. Keyword search searches both the title and the description.

> Ke Xuan a Di**vina**tion Monk from the Judgement Temple has been 

You can restrict your search to the title by opening the advanced search pane.
