### ISSUE TITLE
There is no "Chapters" in the "Order by" of the Advance Search...

### ISSUE THREAD

**Issue by Nocanth** [kanadaj/RoyalRoadLegends#77]
Its hard to find a Long Stories because the "Number of Pages" is kinda confusing

thanks.

**Comment by kanadaj** [comment]
Pages are calculated by simple division of the word count and represent the standard page of a regular printed book, which is a real representation of content length, unlike a chapter count.

**Comment by Nocanth** [comment]
But the Number of pages is also counting the pages of the comments... atleast do something about that

**Comment by kanadaj** [comment]
It doesn't. Do you know how book pages work?
