### ISSUE TITLE
Latest Updates doesn't show fiction rating 

### ISSUE THREAD

**Issue by Joyueguie** [kanadaj/RoyalRoadLegends#79]
I'm leaving this comment again because I feel it is a serious issue. It's not a question of design but of poor utility. I (and others) browse the latest update page and view the stories based on their rankings and number of chapters. Since you've taken off the rankings, I've lost that ability making the the latest updates page practically useless. You've replaced the information that I used with information that I don't care about. A cover (about 50% of the fictions have generic place holder covers) - and tags which I never used anyway. The third thing that I don't like is that the section containing the story info seems far slower to access. It used to be hidden and revealed, now it appears in order to view the story information you have to launch another page. Argh!

**Comment by curvinho** [comment]
To avoid clutter of information, we removed unnecessary information of the lists.
Latest updates show the latest updates, as it should.
