### ISSUE TITLE
layout problem on mobile phone

### ISSUE THREAD

**Issue by Sil0ver** [kanadaj/RoyalRoadLegends#84]
when zooming out on my phone i get this black space on the right screen it doesn't always happen most commenly happens when those ''blue screens'' are used in a chaper

![screenshot_20161009-141300](https://cloud.githubusercontent.com/assets/22665505/19220430/65b2ae22-8e2d-11e6-9658-f3ca14b799e0.png)

**Comment by mjkj** [comment]
might be related to #30 ?

**Comment by Sil0ver** [comment]
http://royalroadl.com/fiction/chapter/96899
After loading that page on my phone and zooming out as much as possile i get those white space on the right

**Comment by Sil0ver** [comment]
Forget to add that it isn't on all pages that i get those white space at the right
