### ISSUE TITLE
[/tr] forum glitch.

### ISSUE THREAD

**Issue by OldBegginings** [kanadaj/RoyalRoadLegends#85]
On the forums, saying '/tr' in square brackets in the forums mid sentence causes [this](http://ust.chatango.com/um/o/l/oldbegginings/img/l_14.jpg) to happen. (To reference, the text above and the message below are the same message, the latter half of the message after the [/tr] got cut off, leaving the signiture, button bar and the latter half of the message above the avatar, former half of the message and stuff.)

**Comment by kanadaj** [comment]
This is an issue with how tables are set up on the forum to make them embedable. tr corresponds with /tr but since the forum's regex engine is not recursive, they have to be parsed separately.
