### ISSUE TITLE
Latest Update page 2 link broken.

### ISSUE THREAD

**Issue by FrankMan2point0** [kanadaj/RoyalRoadLegends#87]
This issue has already been posted and listed as closed twice with #49 and #68.  However I am still seeing this issue myself.

Upon clicking the Latest Updated link in the Reading tab I am taken to [http://royalroadl.com/fictions/latest-updates/](url).  After scrolling down the navigation bar at the bottom looks like this for me. 
![image](https://cloud.githubusercontent.com/assets/22728063/19221313/7ed57d5c-8e06-11e6-9dfc-7f49cc87adc7.png)

The link 1 is irrelevant as that is the current page.  The link 3 takes me to [http://royalroadl.com/fictions/latest-updates/?page=3#results](url) as expected. And the link "Last" takes me to [http://royalroadl.com/fictions/latest-updates/?page=393#results](url) which as no stories or links other than the main bar that is on every page.

Link 2 ![image](https://cloud.githubusercontent.com/assets/22728063/19221335/08a49824-8e07-11e6-830a-661001b779a0.png)takes me to [http://royalroadl.com/fictions/latest-updates/2/#results](url) which says the page cannot be found. 
![image](https://cloud.githubusercontent.com/assets/22728063/19221347/3ac0fd5c-8e07-11e6-90ac-50cfb35f9f0a.png)

From page 3 of the Latest Updated section ([http://royalroadl.com/fictions/latest-updates/?page=3#results](url)) the navigation bar on the bottom looks like this.
![image](https://cloud.githubusercontent.com/assets/22728063/19221352/72a0054c-8e07-11e6-84a8-ab34a4197ee9.png)
All the links here work expect for 2 which continues to direct me to [http://royalroadl.com/fictions/latest-updates/2/#results](url).

I attempted to change the page 3 address (http://royalroadl.com/fictions/latest-updates/?page=3#results) to take me to page 2 by switching the 3 with a 2 (http://royalroadl.com/fictions/latest-updates/?page=2#results) but upon hitting enter it redirected to http://royalroadl.com/fictions/latest-updates/2/#results again.

My current work around to see the latest updates in order and still access page 2 is to do it from the search page by using the advanced search function to change the "ordered by" drop down to Latest updated.  However I would prefer to use the simpler method of just going to the Latest Updated page and scrolling through there.

**Comment by kanadaj** [comment]
Could you tell me what browser you use?

**Comment by FrankMan2point0** [comment]
My primary browser is Google chrome, which says it is up to date.
![image](https://cloud.githubusercontent.com/assets/22728063/19222257/d778d31a-8e19-11e6-878c-4801c1a2e8d0.png)
I did go on to Microsoft Edge and try it there and with that browser the link to the page 2 works.

**Comment by Ultrabenosaurus** [comment]
Have you tried doing a hard refresh (Ctrl + F5 for most browsers on Windows, not sure on other OS) while on page 1? It will reload the page while ignoring any cached data, downloading everything brand-new from the server, so if the fix is client-side like JavaScript then your problem will likely be solved. I can't imagine you'd see one link in Chrome and another in Edge if it wasn't a JS/caching issue.

**Comment by kanadaj** [comment]
I've changed that link a bit ago, can you check if it works now?

**Comment by FrankMan2point0** [comment]
I tried the Ctrl + F5 and I still had the issue.  Tried going to page 2 just now and it still wasn't working with chrome.  Looking at the differences between Edge and Chrome I noticed that when I access the initial Latest Updates page on Edge the address is http://royalroadl.com/fictions/latest-updates but on chrome it is showing as http://royalroadl.com/fictions/latest-updates/ with the extra / on the end.  When I click on the page 3 link on Edge the address is http://royalroadl.com/fictions/latest-updates?page=3 and on Chrome the address is http://royalroadl.com/fictions/latest-updates/?page=3 still keeping the extra / in it.  On Edge when I go to page 2 the link is http://royalroadl.com/fictions/latest-updates?page=2 and when I enter that link in Chrome it works.

**Comment by kanadaj** [comment]
The extra / shouldn't stop it from working.

**Comment by FrankMan2point0** [comment]
I wouldn't have really thought so either especially since page 3 and up all work with that extra / (http://royalroadl.com/fictions/latest-updates/?page=3) but then when you change the number to 2 (http://royalroadl.com/fictions/latest-updates/?page=2) it redirects me to http://royalroadl.com/fictions/latest-updates/2/ which is showing me the Page Cannot be found screen.  Remove that extra / for page 2 (http://royalroadl.com/fictions/latest-updates?page=2) and it and all the other pages continue to work as well.

**Comment by Ultrabenosaurus** [comment]
Well this is odd...

![](http://puu.sh/rDcz0/61f0bec497.jpg)

It works perfectly fine for me, with and without the final slash, in the exact same version of Chrome that @FrankMan2point0 is using.

**Comment by FrankMan2point0** [comment]
Well, Thank you for the help and looking in to it.  Evidently it is just something weird with my browser.
