### ISSUE TITLE
Can't upload a cover image for my story

### ISSUE THREAD

**Issue by NothingToSeeHereMoveAlong** [kanadaj/RoyalRoadLegends#92]
(I am not sure if this is an issue spawnign from the new update, if this is the wrong place to post my problem then tell me and i'll delete it)

So, i need some help. I wanted to upload a cover for one of my novels, it was a sudden and whimsical idea.  So i looked for some pictures, saw one that I liked, noticed it kinda looked like how i described my MC and another character(so in all it was a rather convenient pic that i found well-drawn and such. Really liked it)...And then when i did some editing to it and such, some minor things, I tried to upload it as my cover art. I of course gave credit to the creators of the work and made a link to where i found the picture in my story's page.

However, nothing changed when i uploaded it. I downloaded an app and changed the dimensions to 200x400 exactly. I tried to upload that but it still showed no change. So I then changed it to 400x 600.

This time it was different. It said this: Error: Failed to upload cover image. The remote server returned an error: (400) bad request

The first time when it was 200x300 it said nothing of the sort. Yet i noticed the cover image was still blank.

I suppose what im asking specifically is...does it take time for the picture you upload to be placed as the cover image? If i upload something, would there be a sort of lag or something? Like how it takes a new story to be approved and such?

Is this is a problem with the file type? I dont know much about this. I see a .png when i look at the image details, so do i have to convert it to something different? Just so you know, I tried doing all this on my phone, and this last time i converted the picture to .jpeg using an app. Then I uploaded the picture, with the dimensions of 400x600. This time there was no error reported to me so is this a time lag issue as I mentioned, or is this because of the new update? I'm unsure of what is hapening as this is the first time I ever uploaded a cover.

**Comment by kanadaj** [comment]
It's an issue with the upload that I still haven't had time to figure out. Will fix this ASAP

**Comment by kanadaj** [comment]
Cover upload fixed.
