### ISSUE TITLE
Posting after Editing a Comment shows Deleted Message

### ISSUE THREAD

**Issue by mjkj** [kanadaj/RoyalRoadLegends#94]
After posting an edited comment the "success" message says: Successfully **deleted** the post - see screenshot below. The message is updated perfectly, though, not deleted.
![editcomment](https://cloud.githubusercontent.com/assets/22667034/19242982/f46e3f08-8f15-11e6-9abf-8d094866e30d.jpg)

Label: Enhancement

**Comment by kanadaj** [comment]
Fixed in the next patch
