### ISSUE TITLE
Rating author and users on story threads

### ISSUE THREAD

**Issue by Actzoltan** [kanadaj/RoyalRoadLegends#95]
The new rating buttons both for users and the author of the thread redirect to the main rating page. 
Leaving the only way to rate through member score vs post score. This causes issues tracking where the rating came from. 

Well as i'm kinda a rating fairy i enjoy giving tiny bags of mysterious +1 dust to authors and enjoyed the old way of rating. 

Thanks for the update. ^_^

**Comment by kanadaj** [comment]
The old way, sadly, can't work as we aren't using the forum for the fictions anymore, and trying to make the forum digest a new sort of reputation seems like suicide (the forum is around 1 million lines of PHP code)

**Comment by Actzoltan** [comment]
Ah, well that is understandable just wanted to mention it. Tee hee~ *head tilt, playful bonk*
